version: '2'

services:
  zookeeper:
    image: "jplock/zookeeper:3.4.5"

  mesos_master:
    image: "mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404"
    ports:
      - "5050:5050"
    links:
      - zookeeper:zk
    environment:
      MESOS_ZK: zk://zk:2181/mesos
      MESOS_LOG_DIR: /tmp/logs/master_log
      MESOS_WORK_DIR: /var/lib/mesos

  mesos_slave:
    image: "mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404"
    links:
      - zookeeper
      - mesos_master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/lib/libapparmor.so.1:/usr/lib/libapparmor.so.1:ro
      - /usr/lib/libseccomp.so.2:/usr/lib/libseccomp.so.2:ro
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_ISOLATION: cgroups/cpu,cgroups/mem
      MESOS_DOCKER: /usr/bin/docker

  marathon:
    image: "mesosphere/marathon:v0.16.0-RC3"
    ports:
      - "8888:8080"
    links:
      - zookeeper
      - mesos_master
    environment:
      MARATHON_MASTER: zk://zookeeper:2181/mesos
      MARATHON_ZK: zk://zookeeper:2181/marathon

  dns:
    image: "mesosphere/mesos-dns:0.5.2"
    links:
      - zookeeper
      - mesos_master
